### ISSUE TITLE
请问relRrlStr定义接口是通过什么方式知道的呢

### ISSUE THREAD

**Issue by axiaoxin** [nanlei2000/douyin_download#2]
请问下

```
relRrlStr        = `https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=`
```

这个api是通过什么方式抓取到的呀，木有抓到，而且现在好像掉不通了

**Comment by nanlei2000** [comment]
https://github.com/Johnserf-Seed/TikTokDownload 参考的这个，目前这个也挂了，而且也没找到新的替代接口~

**Comment by myitmx** [comment]
> https://github.com/Johnserf-Seed/TikTokDownload 参考的这个，目前这个也挂了，而且也没找到新的替代接口~

可以参考这个 https://github.com/5ime/video_spider/blob/a171a1376cd45182676c8c4848260d3a8081467e/src/video_spider.php#L39

**Comment by nanlei2000** [comment]
目前已经可以下载视频了，但是图集还不支持（已经有 api 但是需要调整代码结构），有时候再弄下～
